import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from torch import optim

#########  carateristics of the shell model ############

k0 = 0.125    # largest scale
lmb = 2.0     #ratio between consecutive scales
eps =  0.5     # for the NL coefficients
nu = 1.e-7
nb_shell = 22 

K_list = [k0*lmb**i for i in range(nb_shell)]
K = torch.tensor(K_list, dtype=torch.float32)


######### The data generated by the shell model #######
PATH = r"./GOY-main/"
path_data = PATH + "data.dat"

data =  np.loadtxt(path_data)
Data_shell = data[:,::2]
Data_ic = Data_shell[0,:]
Data_bc = Data_shell[:,0:4]
Npts = np.shape(Data_shell)[0]


def filter_mode(X,mode_min:int,t_min:int,ratio:float,seed):
    
    np.random.seed(seed=seed)
    X_subset = np.copy(X)
    X_subset[:,0:mode_min] = None #enlève les modes inférieurs à mode_min
    X_subset[0:t_min,:] = None #enlève la phase de stabilisation
    nb_column = np.shape(X_subset)[1]
    nb_line = np.shape(X_subset)[0]
    X_filtered = np.copy(X_subset)
    X_pos = []
    X_value = []
    X_dataset = []
    for j in range(mode_min,nb_column):
        for i in range(t_min,nb_line):
            if (np.random.random()<=ratio):
                X_filtered[i,j] = X_subset[i,j]
                X_pos.append([i,j])
                X_value.append(X_subset[i,j])

            else:
                X_filtered[i,j] = None
    var_mode = [np.var(X[:,j]) for j in range(nb_column)]
    std_mode = [np.std(X[:,j]) for j in range(nb_column)]
    pourcentage_filtered = nb_line*ratio/nb_line*100
    X_dataset.append(X_pos)
    X_dataset.append(X_value)
    return X_filtered,var_mode,std_mode,pourcentage_filtered,X_dataset

Data_filtered ,Var_mode,Std_mode,perc,Data_train = filter_mode(Data_shell,5,int(0.1*100100),0.001,123456)



############ parameters for the PINN ############

# nb of shells selected for training the PINN
k_min = 0  
k_max = 10
#nb of shells for
k_bc_min = 0
k_bc_max = 4 

class GOY_PINN(nn.Module):

    def __init__(self,n_input,n_output,n_hidden,n_layers):
        super().__init__()

        activation = nn.Tanh
        self.input_layer = nn.Sequential(*[
                                    nn.Linear(n_input, n_hidden),
                                    activation()])

        self.hidden_layers = nn.Sequential(*[
                        nn.Sequential(*[
                            nn.Linear(n_hidden, n_hidden),
                            activation()]) for _ in range(n_layers-1)])

        self.output_layer = nn.Linear(n_hidden, n_output)

    def forward(self,x):

        x=self.input_layer(x)
        x=self.hidden_layers(x)
        x=self.output_layer(x)

        return x


def initial_conditions(X_ic,k_initial,t_initial):
    return X_ic[t_initial,k_initial]

# Dirichlet boundary condition
def boundary_conditions(X_bc,k_boundary,t_boundary):
    u_boundary = X_bc[t_boundary,k_boundary]
    return u_boundary

class initials_variables_data(torch.utils.data.Dataset):
    def __init__(self,X_ic,nbr_initial_t,k_min,k_max):
        #initialise the variables
        # Expect X_ic to be a 2D numpy array: (time, shells)
        self.X_ic = X_ic
        self.nbr_initial_t = nbr_initial_t
        self.k_min = k_min
        self.k_max = k_max
        self.x_initial = np.array([k for k in range(k_min,k_max)],dtype="float32") # shells selected for initial conditions
        self.t_initial = np.array([0 for _ in range(self.nbr_initial_t)],dtype="float32")  # 0 since the initial condition is defined for t=0

    def __len__(self):
        #return the lenght of the dataset
        return self.x_initial.shape[0]*self.t_initial.shape[0]

    def __getitem__(self,idx):
        # return the element in that index
        nx = self.x_initial.shape[0]
        # map idx -> (x_index, t_index)
        i = idx % nx
        j = idx // nx
        k_idx = int(self.x_initial[i])
        t_idx = int(self.t_initial[j])
        value = initial_conditions(self.X_ic, k_idx, t_idx)
        return float(k_idx), float(t_idx), float(value)


# We impose dirichlet with u=0 at the boundaries
class boundary_variables_data(torch.utils.data.Dataset):
    def __init__(self,X_boundary):
        
        #get the data 
        self.X_boundary = X_boundary
        self.nb_k = np.shape(X_boundary)[1]
        self.nb_t = np.shape(X_boundary)[0]

        # keep integer indices for indexing the numpy array
        self.k_boundary = np.array([k for k in range(self.nb_k)],dtype="int64")
        self.t_boundary = np.array([t for t in range(self.nb_t)],dtype="int64")
        self.boundary_t = int(self.nb_t)

    def __len__(self):
        #return the lenght of the dataset
        return self.nb_k*self.nb_t
    def __getitem__(self,idx):
        # return the element in that index
        j = idx // self.boundary_t
        i = idx % self.boundary_t
        val = boundary_conditions(self.X_boundary,int(self.k_boundary[j]),int(self.t_boundary[i]))

        return float(self.k_boundary[j]), float(self.t_boundary[i]), float(val)

class colocations_variables_data(torch.utils.data.Dataset):
    def __init__(self,X_Data_train):
        #initialise the variables
        self.X_Data_train = X_Data_train
        self.nb_colocation_pnt = len(self.X_Data_train[1])
        # self.x = np.linspace(x_min,x_max,N_x,dtype="float32")
        # self.t = np.linspace(t_min,t_max,N_t,dtype="float32")

    def __len__(self):
        #return the lenght of the dataset
        return self.nb_colocation_pnt
    # voir comment go through the dataset  et quoi return for the physics loss

    def __getitem__(self,idx):
        # return the element in that index
        # X_Data_train is [X_pos_list, X_value_list]
        # X_pos_list[idx] = [i, j], X_value_list[idx] = scalar
        pos = self.X_Data_train[0][idx]  # [i, j]
        val = self.X_Data_train[1][idx]  # scalar value
        return float(pos[0]), float(pos[1]), float(val)


class grid_data(torch.utils.data.Dataset):
    def __init__(self,k_min,k_max,t_min,t_max):
        #initialise the variables
        self.k_min = k_min
        self.k_max = k_max
        self.t_min = t_min
        self.t_max = t_max
        self.x = np.array([k for k in range(k_min,k_max)],dtype="float32")
        self.t = np.array([t for t in range(t_min,t_max)],dtype="float32")
        self.N_k = np.shape(self.x)[0] 
        self.N_t = np.shape(self.t)[0]

    def __len__(self):
        #return the lenght of the dataset
        
        return self.N_t*self.N_k
    # voir comment go through the dataset  et quoi return for the physics loss

    def __getitem__(self,idx):
        # return the element in that index
        i = idx % self.N_k      # shell index
        j = idx // self.N_k     # time index
        return float(self.x[i]), float(self.t[j])  # This class only returns the x and t values of the grid not the velocity

class Train_PINN():

    def __init__(self,learning_rate,nbr_iteration,w_1,w_2,w_3,w_4):
        self.learning_rate = learning_rate
        self.nbr_iteration = nbr_iteration
        self.w_1 = w_1
        self.w_2 = w_2
        self.w_3 = w_3
        self.w_4 = w_4
        self.optimizer = torch.optim.Adam(model.parameters(),lr = self.learning_rate)
        
    def train(self):
        loss = np.zeros((self.nbr_iteration,1))
        for iteration in range(self.nbr_iteration):
            self.optimizer.zero_grad()

            #initial conditions Loss
            # build tensor from dataset (columns: k, t, u)
            initial_list = [initial_train_dataset[i] for i in range(len(initial_train_dataset))]
            initial_rows = [[float(x), float(t), float(u)] for x,t,u in initial_list]
            initial_train_data = torch.tensor(initial_rows, dtype=torch.float32)
            u_pd_ini = model(initial_train_data[:, 0:2])
            u_exa_ini = initial_train_data[:,2:3]
            loss_initital_conditions = self.w_1*torch.mean((u_pd_ini-u_exa_ini)**2)

            #Boundary conditions Loss
            boundary_list = [boundary_train_dataset[i] for i in range(len(boundary_train_dataset))]
            boundary_rows = [[float(x), float(t), float(u)] for x,t,u in boundary_list]
            boundary_train_data = torch.tensor(boundary_rows, dtype=torch.float32)
            u_pd_bou = model(boundary_train_data[:, 0:2])
            u_exa_bou = boundary_train_data[:,2:3]
            loss_boundary_conditions = self.w_2*torch.mean((u_pd_bou-u_exa_bou)**2)

            

            #Physical and colocation Loss
            colocation_list = [colocation_dataset[i] for i in range(len(colocation_dataset))]
            # extract positions and values for colocation loss
            colocation_positions = [[float(x), float(t)] for x,t,v in colocation_list]
            colocation_values = [[float(v)] for x,t,v in colocation_list]
            colocation_pos_tensor = torch.tensor(colocation_positions, dtype=torch.float32).requires_grad_(True)
            colocation_tensor = torch.tensor(colocation_values, dtype=torch.float32)

            # Forward pass on colocation points only
            u_pd_coloc = model(colocation_pos_tensor)
            loss_colocation = self.w_3*torch.mean((u_pd_coloc-colocation_tensor)**2)

            # Forward pass on full grid for physics loss
            grid_list = [grid_dataset[i] for i in range(len(grid_dataset))]
            grid_rows = [[float(x), float(t)] for x,t in grid_list]
            train_data = torch.tensor(grid_rows, dtype=torch.float32).requires_grad_(True)

            u_pd = model(train_data)
            #a = torch.autograd.grad(u_pd, train_data, torch.ones_like(u_pd), create_graph=True)
            grads = torch.autograd.grad(u_pd, train_data, torch.ones_like(u_pd), create_graph=True)[0]
            u_t = grads[:,1:2]  # time derivative
            # u_x = torch.autograd.grad(u_pd, train_data, torch.ones_like(u_pd), create_graph=True)[0][:,0:1]
            # u_xx = torch.autograd.grad(u_x, train_data, torch.ones_like(u_pd), create_graph=True)[0][:,0:1]
            #physics = u_t + u_pd*u_x - nu*u_xx
            # faire la somme sur les shells
            # for i in range (2,nb_shell-2):
            # Note: reshape tensors to work per-shell
            # Reshape grid_rows back to (N_t, N_k) to map shells and times
            N_k = len(grid_dataset.x)
            N_t = len(grid_dataset.t)
            u_pd_grid = u_pd.view(N_t, N_k)  # (N_t, N_k)
            u_t_grid = u_t.view(N_t, N_k)   # (N_t, N_k)
            
            physics_terms = []
            for i in range (k_min+2,k_max-2):
                if i+2 < N_k and i-2 >= 0:  # ensure indices are valid
                    term = u_t_grid[:,i] - K[i]*u_pd_grid[:,i+1]*u_pd_grid[:,i+2] + K[i]*eps/lmb*u_pd_grid[:,i-1]*u_pd_grid[:,i+1] - K[i]*((eps-1)/lmb**2)*u_pd_grid[:,i-2]*u_pd_grid[:,i-1] + nu*K[i]*K[i]*u_pd_grid[:,i]
                    physics_terms.append(term.unsqueeze(-1))
            if len(physics_terms) > 0:
                GOY_physics = torch.cat(physics_terms, dim=0)
                loss_physics = self.w_4*torch.mean(GOY_physics**2)
            else:
                loss_physics = torch.tensor(0.0, requires_grad=True)

            #Total Loss
            total_loss = loss_initital_conditions + loss_boundary_conditions + loss_physics + loss_colocation
            total_loss.backward()
            self.optimizer.step()
            loss[iteration]=total_loss.detach().numpy()
            
        return loss





torch.manual_seed(119)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GOY_PINN(n_input=2,n_output=1,n_hidden=20,n_layers=8)

# nbr_initial_x = N_x   # N_x samples in space for the definition of the initial condition
nbr_initial_t = 1     # Only t=0 for defining the initial condition

# boundary_x = 2    # Boundary conditions of a 1d solution
# boundary_t = N_t  # Boundary conditions for any time
t_min = 0
t_max = Npts

initial_train_dataset = initials_variables_data(Data_shell,nbr_initial_t,k_min,k_max)
boundary_train_dataset = boundary_variables_data(X_boundary=Data_bc)
colocation_dataset = colocations_variables_data(Data_train)
grid_dataset = grid_data(k_min,k_max,t_min,t_max)

learning_rate,nbr_iteration,w_1,w_2,w3,w_4 = 0.005,300,1,1,1,1
t = Train_PINN(learning_rate,nbr_iteration,w_1,w_2,w3,w_4)
Total_loss = t.train()